# Generated by Django 6.0.4 on 2026-05-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='logo',
            field=models.ImageField(blank=True, upload_to='about/'),
        ),
    ]
