# Generated by Django 6.0.4 on 2026-09-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.FileField(blank=True, upload_to='partners/'),
        ),
    ]
