# Generated by Django 6.0.4 on 2026-09-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_partner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/about'),
        ),
    ]
