# Generated by Django 6.0.4 on 2026-05-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('legal', 'Legal')], max_length=15),
        ),
    ]
