# Generated by Django 6.0.4 on 2026-05-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('legal', 'Legal')], default='individual', max_length=15),
        ),
    ]
