# Generated by Django 6.0.4 on 2026-05-11 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=19, validators=[django.core.validators.RegexValidator('^\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$', 'Format: +375 (29) XXX-XX-XX')]),
        ),
    ]
