# Generated by Django 6.0.4 on 2026-05-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('client', 'Client'), ('admin', 'Admin')], default='client', max_length=15),
        ),
    ]
